### ISSUE TITLE
Monad-Coroutine break

### ISSUE THREAD

**Issue by ghost** [tweag/monad-bayes#109]
**Describe the bug**
Installation of the package fails from hackage, so does building from source. I received an error during building that said building monad-coroutine-0.9.1 failed with an error about MonadFail not being defined.

**To Reproduce**
Either running `cabal install monad-bayes` or building the source code should reproduce. 

**Expected behavior**
Package to install without a problem.

**Environment**
 - OS name + version: Pop OS 20.04
 - Version of the code: 0.1.1

**Additional context**
Fixing the monad-coroutine package to 0.9.0.4 solved the issue, I suspect the problem comes from version 0.9.1. I can open a pull request for this to temporarily fix the version, until monad-coroutine is fixed.

**Comment by curiousleo** [comment]
Thanks for the report!

I can't repro that failure with GHC 8.10. On tag `0.1.1.0` with this patch:

```diff
--- a/monad-bayes.cabal
+++ b/monad-bayes.cabal
@@ -58,7 +58,7 @@ library

     other-extensions:   ScopedTypeVariables DeriveFunctor
     build-depends:
-        base >=4.11 && <4.14,
+        base >=4.11 && <4.15,
         containers >=0.5.10 && <0.7,
         free >=5.0.2 && <5.2,
         ieee754 >=0.8.0 && <0.9,
```

and

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.4
$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
```

I get:

```
$ cabal build
[ ... succeeds ... ]
$ cabal test
[ ... succeeds ... ]
```

I'm going to update our build matrix to include GHC 8.10 and with the necessary version bound changes over the coming week or so. But that is just prompted by your report, it doesn't really address it.

I can try repro'ing with an older GHC version if you let me know which one you used.

**Comment by ghost** [comment]
@curiousleo The version I am using is GHC 8.6.5 and cabal 2.4.0.0. Perhaps these tools are too old for some new feature used in the newer build of ``monad-coroutine``? For more clarity, here is the error I receive while building

```Control/Monad/Coroutine.hs:108:38: error:
    Not in scope: type constructor or class ‘MonadFail’
    |
108 | instance (Functor s, MonadFail m) => MonadFail (Coroutine s m) where
    |                                      ^^^^^^^^^
cabal: Failed to build monad-coroutine-0.9.1 (which is required by exe:example
from monad-bayes-0.1.1.0). See the build log above for details.```

**Comment by curiousleo** [comment]
@AlricRahl that sounds likely -- are you able to try this with a newer GHC version? Since the failure is clearly in the `monad-coroutine` build, I'm not going to look into this too deeply right now.
