### ISSUE TITLE
Updated docs 

### ISSUE THREAD

**Issue by reubenharry** [tweag/monad-bayes#127]
- [x] documentation (of which a draft is https://monad-bayes.netlify.app/)
- [x] a tutorial, in notebook form, covering independent sampling, MCMC, particle filters, rmsmc, pmmh, smc2 (https://probmods.org/ is an excellent example of how to do this well (in that case the focus is on using probabilistic programming to model cognition) )
- [x] update the haddock docs with more comments (e.g. difference between different resamplers)
- [x] update hackage to link to the docs and tutorials

The broad goal is to make monad-bayes accessible to anyone with a beginner understanding of Haskell and a beginner understanding of Bayesian inference. That will require clear tutorials with simple working examples.

**Comment by idontgetoutmuch** [comment]
This is great - I am writing up an example of PMMH independent of monad-bayes - I've put notes in pdf form here:

[odeModelExpanded.pdf](https://github.com/tweag/monad-bayes/files/8253569/odeModelExpanded.pdf)

The code is here:

1. https://github.com/idontgetoutmuch/abm-particle-filter/blob/mathematical-exposition/src/Data/PMMH.hs#L42
2. https://github.com/idontgetoutmuch/abm-particle-filter/blob/mathematical-exposition/src/Data/PMMH.hs#L93

I've also used [Stan](https://mc-stan.org/) to infer the parameters albeit for a slightly(?) different model (one that is fully deterministic once you know the parameters). This is included in the pdf above and in the git repo.

**Comment by MMesch** [comment]
This looks great. Looking forward to the PR. I can iterate through it.

**Comment by reubenharry** [comment]
Thanks for those notes! One of the more time-intensive parts of the docs that I haven't yet done is to have a worked through example of PMMH, so I may use your notes as reference material for writing that.

**Comment by idontgetoutmuch** [comment]
@reubenharry I don't know how much mathematical detail you want to put in the docs. I think the Stan documentation is great but even that does not try to explain Hamiltonian Monte Carlo. Ah but it does here: https://mc-stan.org/docs/2_29/reference-manual/hamiltonian-monte-carlo.html although not particularly rigorously or in great detail. Anyway I am nowhere near finished explaining HMC let alone how one can use it to approximate the posterior (log) likelihood for use in MCMC (or even HMC). You can see what you think when I have finished. I am attempting to make it accessible to a widish audience while still remaining mathematically unsullied :-)

**Comment by reubenharry** [comment]
I'm definitely very in favour of mathematical detail as long as it's presented in a way that doesn't obscure the high level picture. My thinking (somewhat influenced by https://documentation.divio.com/) was that we could divide the various documentation-like things into:

- examples of uses (presented in jupyter notebook form - I'm starting to work on this, building on what Matthias has done so far). This would include e.g. a differential equation example of PMMH, MH for logistic regression, a state space model, something non-parametric, and so on. I like the idea of doing this in notebooks so it's easy to throw up graphs.
- API reference (basically what I did here: https://monad-bayes.netlify.app/probprog.html and also what's on Hackage)
- developer docs explaining the architecture of the code (basically what I did here: https://monad-bayes.netlify.app/usage.html)
- technical reference for the statistical concepts (either our own, or links to good ones). I'm imagining this would include explanations of HMC, PMMH, etc. 
- A gallery of applications. I have a range of cute combinations of other Haskell libraries and monad-bayes, including pipes, parsec, lens, recursion-schemes and aeson. Would be nice to polish these and put them somewhere, but probably in a separate repo called monad-bayes-app (so that monad-bayes doesn't incur loads of new dependencies)

**Comment by reubenharry** [comment]
@idontgetoutmuch The one last thing I'd like to do here is to have a link on hackage to the website or the github repo, so that it's clear that's the place to go for a readme. I'm not experienced with Haddocks - do you know where I'd put that info so it appears on the front page of the docs on hackage?

**Comment by idontgetoutmuch** [comment]
How does this look? https://hackage.haskell.org/package/monad-bayes-1.1.0/candidate

**Comment by reubenharry** [comment]
Perfect! (There's only quotation mark that I think is a typo)
