### ISSUE TITLE
Warnings and error messages

### ISSUE THREAD

**Issue by reubenharry** [tweag/monad-bayes#129]
A big part of making monad-bayes usable is to have warnings and error messages that guide users. Issue #121 is a good example: the MCMC chain was never accepting proposals, and it would have been much easier to debug if there had been a warning message like "MCMC chain fails n% of the time. This suggests that the proposal needs improvement."

Other warnings and errors:
- if initial sample in MCMC chain has zero probability, that should probably be an error, but at least a warning
- if MCMC chain doesn't seem to be converging, that should be a warning
- if SMC is used in a model with only a single factor statement, that should raise a warning like: "Are you sure you want to use SMC here? This model only has a single factor, so won't benefit from it." 

A somewhat related issue that I'll lump into this is to add some reporting to an MCMC run, like percentage acceptance, time taken, and maybe even a progress bar. (Note: the natural transformation in `sis` could update a progress bar at each step of SMC)

**Comment by reubenharry** [comment]
After a little thought and hacking, I think there should be functions like `runMH`, that act as friendly wrappers around core inference methods like `mh`. These would run the algorithm, displaying nice command line info perhaps using [brick](https://hackage.haskell.org/package/brick) and offer helpful warnings and error messages. I'll start out with ones for rejection sampling and mh.

**Comment by idontgetoutmuch** [comment]
@reubenharry one of my colleagues @UnkindPartition used https://hackage.haskell.org/package/katip-0.8.7.0 and I am also using it in my blog post on SMC. I didn't research alternatives but AFAICT you can log things at varying levels of detail. I don't know what it means for performance though. I hoping it has minimal impact as it is being used for an ODE solver where you really do want performance but I have no performance data on which to base that.
