### ISSUE TITLE
Automatic MonadDist derivation

### ISSUE THREAD

**Issue by adscib** [tweag/monad-bayes#15]
We often provide `MonadDist` instances by lifting distributions from the transformed monad. Currently this is only done for `primitive`, which means that all the specialised implementations of distributions used by the transformed monad are lost. We should instead lift all of them from the transformed monad, bearing in mind that more distributions can be added to `MonadDist` in the future.

I'm not sure what's the best way to do it. Metaprogramming and a compiler extension for automatic derivation come to mind.

**Comment by reubenharry** [comment]
Closing as this issue no longer aligns with the code architecture.
