### ISSUE TITLE
Source of Parsing notebook?

### ISSUE THREAD

**Issue by ocramz** [tweag/monad-bayes#164]
**Is your feature request related to a problem? Please describe.**
I cannot seem to find the notebook that renders into Parsing.html . Could you add it to the repository please?

**Comment by reubenharry** [comment]
Ah, you should be able to find it on branch: https://github.com/tweag/monad-bayes/tree/notebooks/notebooks/examples . The draft website is a little ahead of the main branch, as I'm waiting on some reviews before merging stuff.

I think there's probably some really interesting things involving probabilistic parser combinators, but I don't know that what I did in the notebook necessarily makes sense. If you have thoughts/ideas, lmk!
