### ISSUE TITLE
unable to commit changes to repo fork

### ISSUE THREAD

**Issue by aleeusgr** [tweag/monad-bayes#173]
**Describe the bug**
when trying to commit changes to the repo get and error:
` 'pre-commit' not found.  Did you forget to activate your virtualenv?`

**To Reproduce**
fork the repo, clone locally, make changes, add then run
`git commit -m 'message'`

**Expected behavior**
`git commit` should work as expected

**Environment**
 - OS name + version: Linux nixos 5.15.59
 - Version of the code: 

**Additional context**

**Comment by reubenharry** [comment]
I think this is something to do with being in a nix-shell. Have you tried this after doing e.g. nix-shell -p ormolu? You can commit with "--no-verify" if this doesn't work.

**Comment by aleeusgr** [comment]
`--no-verify` worked, thank you.

**Comment by aleeusgr** [comment]
I could reproduce the issue by adding pre-commits to flake output. Maybe it happens because pre-commit-hooks are in ~ but not in current repo?
I've no idea,
