### ISSUE TITLE
T in the transformer names

### ISSUE THREAD

**Issue by reubenharry** [tweag/monad-bayes#189]
Sequential -> SequentialT
Traced -> TracedT
Population -> PopulationT
run[X] -> run[X]T

This helps Haskellers understand what is going on better.
```[tasklist]
### Tasks
- [ ] Sequential
- [ ] Traced
- [ ] Population
- [ ] Weighted
- [ ] Density
- [ ] Sampler
- [ ] run* functions
```

**Comment by aleeusgr** [comment]
I'd love to help, but this does not make sense to me.

If you'd shared a doc on what is "transformer", how to find them in the code, I'd think of this as a task I could do.

Thanks.

**Comment by reubenharry** [comment]
Hi. Sure, I can clarify! 

How familiar are you with Haskell? If not, it's actually ok for this one, because basically what I'm suggesting is just a renaming, as follows:

Everywhere "Sequential" appears in the code, we replace it with "SequentialT". So the type `Sequential` becomes `SequentialT`, the constructor `Sequential` also becomes `SequentialT` and `runSequential` becomes `runSequentialT`. 

Similarly for `Population` and `Traced`. 

I think search and replace would mostly work for this.

**Comment by aleeusgr** [comment]
I'm ok with Haskell, not a brightest of minds but I'm learning:)
there's only four of them?
Ok, search and replace, on it.

`grep -rnw -e 'Sequential' --include \*.hs`

**Comment by aleeusgr** [comment]
`find . -type f -exec sed -i 's/Sequential/SequentialT/g' {} \;`

https://stackoverflow.com/questions/15402770/how-to-search-and-replace-using-grep

Hm, It breaks git repo...

`find ./*.hs -type f -exec sed -i 's/Sequential/SequentialT/g' {} \;` ??

**Comment by aleeusgr** [comment]
`find . -name "*.hs" -type f -exec sed -i 's/<oldname>/<newname>/g' {} \;`

also not to forget to rename .hs files and tests; update monad-bayes.cabal

**Comment by aleeusgr** [comment]
Hey @reubenharry 
I figured out Sequential, Traced and Population - `stack test` is passing.
but what's up with run[X]?

`$ grep -rnw -e 'run' --include \*.hs`
returns 
```
test/TestSequentialT.hs:22:finishedTwoSync n = finished (run n twoSync)
test/TestSequentialT.hs:24:    run 0 d = d
test/TestSequentialT.hs:25:    run k d = run (k - 1) (advance d)
test/TestSequentialT.hs:46:isFinished n = finished (run n sprinkler)
test/TestSequentialT.hs:48:    run 0 d = d
test/TestSequentialT.hs:49:    run k d = run (k - 1) (advance d)
src/Control/Monad/Bayes/TracedT/Dynamic.hs:100:-- | Full run of the Trace Metropolis-Hastings algorithm with a specified
src/Control/Monad/Bayes/TracedT/Static.hs:85:-- | Full run of the Trace Metropolis-Hastings algorithm with a specified
src/Control/Monad/Bayes/TracedT/Basic.hs:80:-- | Full run of the Trace Metropolis-Hastings algorithm with a specified
src/Control/Monad/Bayes/Inference/Lazy/MH.hs:35:  -- Now run step over and over to get a stream of (tree,result,weight)s.
src/Control/Monad/Bayes/Inference/TUI.hs:156:  _ <- forkIO $ run (mcmcP MCMCConfig {numBurnIn = burnIn, proposal = SingleSiteMH, numMCMCSteps = -1} distribution) eventChan n
src/Control/Monad/Bayes/Inference/TUI.hs:179:    run prod chan i =
```

I don't see anything that looks like a function.

Cheers.

**Comment by aleeusgr** [comment]
@reubenharry created a PR
