### ISSUE TITLE
Alternative and MonadPlus instance for Dist

### ISSUE THREAD

**Issue by phischu** [tweag/monad-bayes#26]
If you have an [`Alternative`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Applicative.html#t:Alternative) instance for `Dist` your `condition` function would be [`guard`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Monad.html#v:guard).

``` haskell
instance Alternative (Dist r) where
  empty = Dist []
  Dist d1 <|> Dist d2 = Dist (d1 ++ d2)
```

Other distribution types might also allow an `Alternative` instance.

**Comment by adscib** [comment]
Thanks for the suggestion. I think it does actually make sense for many other distribution types to be instances of `Alternative`.
