### ISSUE TITLE
Any way for outsiders to help?

### ISSUE THREAD

**Issue by currymj** [tweag/monad-bayes#41]
I've been following this library with interest for a while. Recently I've noticed that lots of changes are happening. Is there a big release coming up? Any help needed, e.g. around documentation, examples, or testing?

**Comment by adscib** [comment]
Indeed, there's an official release coming up. It's almost ready, I just keep getting distracted with writing papers. It will be based on the content of the `simple` branch.

I could certainly use some help with writing examples. I was thinking of implementing a state-space model and running the inference algorithms available in`Control.Monad.Bayes.Inference` on it. A simple state-space model is available in `models/NonlinearSSM.hs`. All that's missing is a way to evaluate the results of approximate inference. If you're generally familiar with state-space models and how to evaluate results of approximate inference in them, a document that shows how to run different inference algorithms on such a model and then evaluates their results by plotting some metrics would make a great contribution. If you'd rather contribute in some other way let me know and we can think of something - there's plenty to be done from small improvements to substantial features.

**Comment by pengstrom** [comment]
Is there any performance or expressiveness difference between the `simple` and `master` branches?

**Comment by tmcgilchrist** [comment]
@adscib do you have a sense of / timeline for when there might be an official release? And what sort of things you'd like finished before you are happy to do that release?

**Comment by adscib** [comment]
@pengstrom expressiveness should be the same. `master` implements better inference algorithms so should be more performant although less usable.

**Comment by adscib** [comment]
@tmcgilchrist I just need to write a few tests and add a user's guide. It should only be a few days of work, the only problem is to find those days. But thanks for expressing interest, that will help get it done more quickly.

**Comment by tmcgilchrist** [comment]
Thanks for the update. If I am able to help in some way with getting it
released let me know. Happy to proof read or test out a users guide.

**Comment by idontgetoutmuch** [comment]
This seems stale but feel free to re-open.
