### ISSUE TITLE
Is it possible to implement Gaussian Processes based on monad-bayes?

### ISSUE THREAD

**Issue by vincent-hui** [tweag/monad-bayes#47]
Is it possible to implement Gaussian Processes based on monad-bayes?
If yes, would you mind giving me some hints how to implement Gaussian Processes based on monad-bayes?

**Comment by reubenharry** [comment]
Belatedly: this paper has an implementation of Gaussian processes not in monad-bayes, but in a related Haskell probabilistic programming language: https://openreview.net/forum?id=yHox9OyegeX. I'll leave this issue open, as it would be nice, eventually, to incorporate the lazy sampler from LazyPPL into monad-bayes, and define gaussian processes etc.

**Comment by reubenharry** [comment]
@vincent-hui Very belatedly: https://github.com/turion/rhine/tree/dev_monad_bayes/rhine-bayes can do Gaussian processes. It's under construction, and will probably be a separate library that imports monad-bayes. See https://github.com/reubenharry/rhine-bayes-examples#readme for explanation. 

I'll now close this issue

**Comment by turion** [comment]
`rhine-bayes` has since been merged on `master`, but Gaussian processes are not yet merged. See https://github.com/turion/rhine/issues/217.
