### ISSUE TITLE
Publish to Hackage/Stackage

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/monad-bayes#57]
Would it be possible to release on Hackage/Stackage ?
It would be way more convenient.

Thanks

**Comment by adscib** [comment]
I looked into uploading to Hackage but was told the library is missing appropriate version bounds on dependencies. I don't have the time to deal with this right now but if there's a volunteer who'd be willing to sort out the right bounds and put them in the cabal file I can make a release as soon as it's done.

**Comment by YPares** [comment]
@adscib Hackage only asks for boundaries on `base`, not on all deps normally

**Comment by adscib** [comment]
This is what I was told.

>  I also noticed that your package
does not currently have correct version bounds for some of its
dependencies. For instance:
>
> https://github.com/adscib/monad-bayes/blob/master/monad-bayes.cabal#L53-L64
> 
> Packages that are uploaded to Hackage are generally expected to follow
> the Package Versioning Policy and have version bounds on all
> dependencies indicating which versions they are known to build with.
> Here are some links that have more information:
> 
> https://hackage.haskell.org/upload#versioning_and_curation
> https://pvp.haskell.org/
> 
> Also, here are a few things to keep in mind when uploading to Hackage
> that help keep the ecosystem working reliably for everyone:
> 
> 1. Hackage is intended to be a permanent record. Therefore uploads
> cannot be changed or removed.
> 2. Only upload things that work, are useful to other people, and that
> you intend to maintain.
> 3. Use `cabal gen-bounds` to put PVP-compliant version bounds (lower
> AND upper) on ALL your unique dependencies so your package will still
> be buildable years down the road. One important thing to note is that
> you only need to include version bounds once. For example, if you
> depend on the same package in your library and your test suite, you
> only need to put the version bounds for that dependency in one place.
> This keeps the dependency bounds information DRY.
> 4. Package candidates CAN be changed, so use them to test things out
> and get everything right before you publish permanently to the main
> index.

**Comment by curiousleo** [comment]
https://github.com/adscib/monad-bayes/pull/60 contains the version bounds necessary to publish `monad-bayes` to Hackage.

**Comment by curiousleo** [comment]
`monad-bayes` v0.1 is now on Hackage: https://hackage.haskell.org/package/monad-bayes-0.1.0.0

**Comment by curiousleo** [comment]
`monad-bayes` is now on Stackage: https://github.com/commercialhaskell/stackage/pull/5189

**Comment by curiousleo** [comment]
Done!
