### ISSUE TITLE
Build with "-Werror" in CI

### ISSUE THREAD

**Issue by curiousleo** [tweag/monad-bayes#66]
https://github.com/tweag/monad-bayes/pull/63 introduced the `dev` flag for use in development and CI. Currently there are deprecation warnings that would make the build fail if we added `-Werror`. So let's fix those warnings and then set `-Werror` to make sure we don't regress.

- [ ] Get rid of all warnings
- [ ] Add the `-Werror` GHC flag if `dev` is set

**Comment by curiousleo** [comment]
Related: https://github.com/tweag/monad-bayes/pull/63#pullrequestreview-360345213

**Comment by curiousleo** [comment]
One set of warnings that should be easy to fix:

<pre>/home/leo/Code/monad-bayes/<b>models/HMM.hs:28:1: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wincomplete-patterns</b></font><b>]</b>
    Pattern match(es) are non-exhaustive
    In an equation for ‘trans’:
        Patterns not matched: p where p is not one of {2, 1, 0}
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>28 |</b></font> <font color="#75507B"><b>trans 0 = categorical $ fromList [0.1, 0.4, 0.5]</b></font>
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...</b></font>
                           
/home/leo/Code/monad-bayes/<b>models/HMM.hs:35:3: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wincomplete-patterns</b></font><b>]</b>
    Pattern match(es) are non-exhaustive
    In an equation for ‘mean’:
        Patterns not matched: p where p is not one of {2, 1, 0}
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>35 |</b></font>   <font color="#75507B"><b>mean 0 = -1</b></font>         
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b>   ^^^^^^^^^^^...</b></font>      
[3 of 5] Compiling LDA [Control.Monad.Bayes.Class changed]
                           
/home/leo/Code/monad-bayes/<b>models/LDA.hs:37:5: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wname-shadowing</b></font><b>]</b>
    This binding for ‘docs’ shadows the existing binding
      defined at models/LDA.hs:19:1
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>37 |</b></font> lda <font color="#75507B"><b>docs</b></font> = do         
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b>     ^^^^</b></font>              
[4 of 5] Compiling LogReg [Control.Monad.Bayes.Class changed]
[5 of 5] Compiling Main [Control.Monad.Bayes.Traced changed]
                           
/home/leo/Code/monad-bayes/<b>benchmark/Single.hs:1:1: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wunused-imports</b></font><b>]</b>
    The import of ‘GenIO’ from module ‘System.Random.MWC’ is redundant
<font color="#3465A4"><b>  |</b></font>                        
<font color="#3465A4"><b>1 |</b></font> <font color="#75507B"><b>import System.Random.MWC (createSystemRandom, GenIO)</b></font>
<font color="#3465A4"><b>  |</b></font><font color="#75507B"><b> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>benchmark/Single.hs:4:1: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wunused-imports</b></font><b>]</b>
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
<font color="#3465A4"><b>  |</b></font>                        
<font color="#3465A4"><b>4 |</b></font> <font color="#75507B"><b>import Data.Semigroup ((&lt;&gt;))</b></font>
<font color="#3465A4"><b>  |</b></font><font color="#75507B"><b> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>benchmark/Single.hs:12:1: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wunused-imports</b></font><b>]</b>
    The import of ‘Control.Monad.Bayes.Sequential’ is redundant
      except perhaps to import instances from ‘Control.Monad.Bayes.Sequential’
    To import instances alone, use: import Control.Monad.Bayes.Sequential()
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>12 |</b></font> <font color="#75507B"><b>import Control.Monad.Bayes.Sequential</b></font>
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>
</pre>

**Comment by curiousleo** [comment]
The other set of warnings relates to the deprecation of `Control.Monad.Trans.List`, which is probably going to be more work than the above:


<pre>/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Class.hs:65:1: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    Module ‘Control.Monad.Trans.List’ is deprecated:
      This transformer is invalid on most monads
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>65 |</b></font> <font color="#75507B"><b>import Control.Monad.Trans.List</b></font>
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Class.hs:279:40: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of type constructor or class ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>    |</b></font>                      
<font color="#3465A4"><b>279 |</b></font> instance MonadSample m =&gt; MonadSample (<font color="#75507B"><b>ListT</b></font> m) where
<font color="#3465A4"><b>    |</b></font><font color="#75507B"><b>                                        ^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Class.hs:284:36: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of type constructor or class ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>    |</b></font>                      
<font color="#3465A4"><b>284 |</b></font> instance MonadCond m =&gt; MonadCond (<font color="#75507B"><b>ListT</b></font> m) where
<font color="#3465A4"><b>    |</b></font><font color="#75507B"><b>                                    ^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Class.hs:287:38: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of type constructor or class ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>    |</b></font>                      
<font color="#3465A4"><b>287 |</b></font> instance MonadInfer m =&gt; MonadInfer (<font color="#75507B"><b>ListT</b></font> m)
<font color="#3465A4"><b>    |</b></font><font color="#75507B"><b>                                      ^^^^^</b></font>
[ 2 of 17] Compiling Control.Monad.Bayes.Enumerator
[ 3 of 17] Compiling Control.Monad.Bayes.Free
[ 4 of 17] Compiling Control.Monad.Bayes.Sampler
[ 5 of 17] Compiling Control.Monad.Bayes.Sequential
[ 6 of 17] Compiling Control.Monad.Bayes.Weighted
[ 7 of 17] Compiling Control.Monad.Bayes.Traced.Common
[ 8 of 17] Compiling Control.Monad.Bayes.Traced.Static
[ 9 of 17] Compiling Control.Monad.Bayes.Traced
[10 of 17] Compiling Control.Monad.Bayes.Traced.Dynamic
[11 of 17] Compiling Control.Monad.Bayes.Traced.Basic
[12 of 17] Compiling Control.Monad.Bayes.Population
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Population.hs:37:1: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    Module ‘Control.Monad.Trans.List’ is deprecated:
      This transformer is invalid on most monads
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>37 |</b></font> <font color="#75507B"><b>import Control.Monad.Trans.List</b></font>
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Population.hs:48:48: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of type constructor or class ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>48 |</b></font> newtype Population m a = Population (Weighted (<font color="#75507B"><b>ListT</b></font> m) a)
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b>                                                ^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Population.hs:57:32: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of ‘runListT’ (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>57 |</b></font> runPopulation (Population m) = <font color="#75507B"><b>runListT</b></font> $ runWeighted m
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b>                                ^^^^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Population.hs:65:46: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of data constructor ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>   |</b></font>                       
<font color="#3465A4"><b>65 |</b></font> fromWeightedList = Population . withWeight . <font color="#75507B"><b>ListT</b></font>
<font color="#3465A4"><b>   |</b></font><font color="#75507B"><b>                                              ^^^^^</b></font>
                           
/home/leo/Code/monad-bayes/<b>src/Control/Monad/Bayes/Population.hs:182:39: </b><font color="#75507B"><b>warning:</b></font><b> [</b><font color="#75507B"><b>-Wdeprecations</b></font><b>]</b>
    In the use of data constructor ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: &quot;This transformer is invalid on most monads&quot;
<font color="#3465A4"><b>    |</b></font>                      
<font color="#3465A4"><b>182 |</b></font> flatten m = Population $ withWeight $ <font color="#75507B"><b>ListT</b></font> t where
<font color="#3465A4"><b>    |</b></font><font color="#75507B"><b>    </b></font></pre>

**Comment by mrkkrp** [comment]
Can we just drop `ListT`?

**Comment by curiousleo** [comment]
> Can we just drop `ListT`?

Could you explain what you mean by "drop" in this context? Literally deleting every occurrence of `ListT` is not going to compile :)

**Comment by mrkkrp** [comment]
Remove support for the `ListT` monad transformer.
