### ISSUE TITLE
User's guide

### ISSUE THREAD

**Issue by adscib** [tweag/monad-bayes#8]
We need a user's guide to show people how to use the library. I like the style used by [Hspec](http://hspec.github.io/).

Tentative table of contents:
1. MonadDist and MonadBayes type classes
2. How to write models
3. Existing inference algorithms
4. Inference by composition of monad transformers
5. How to write a new inference algorithm

**Comment by reubenharry** [comment]
Closing this as it's subsumed by other issues about documentation. Current draft of new docs at: https://monad-bayes.netlify.app/
