### ISSUE TITLE
graphical rendering of Bayesian networks ?

### ISSUE THREAD

**Issue by ocramz** [tweag/monad-bayes#80]
Would it be possible to render the "reified" network in graphviz or similar? I suspect that the current, Monad-based implementation is a fundamental limitation for this, but I cannot articulate why.

**Comment by curiousleo** [comment]
Hi @ocramz! That certainly sounds useful. I don't know if it is possible. The current focus of work in this repo is on making it easier to build and maintain over the long term, we're not adding features right now. However, you're very welcome to take a stab at this if you like.

**Comment by reubenharry** [comment]
@ocramz Note that a probabilistic program need not be a (finite) graph. There isn't currently a static way to restrict to probabilistic programs which are finite acyclic graphs (i.e. Bayes nets). That said, I could probably write a function to display an execution trace of a probabilistic program as a graph, using e.g. diagrams/graphviz, which I think would be a nice tool. In the case of probabilistic programs which happened to be well-behaved Bayes nets, this would give you what you want, I think.
