### ISSUE TITLE
Build with stack requires manual intervention

### ISSUE THREAD

**Issue by dschrempf** [tweag/monad-bayes#96]
Building with `stack` requires one of the folllowing commands:
```
ln -s stack-ghc844.yaml stack.yaml
ln -s stack-ghc865.yaml stack.yaml
ln -s stack-ghc881.yaml stack.yaml
```
I suggest mentioning this in the Readme.

**Comment by curiousleo** [comment]
Good point, thanks! I've wanted to overhaul the "Installation" part of the Readme for a while.

The installation instructions stem from before the time `monad-bayes` was available on Hackage and Stackage.

Now that `monad-bayes` is on Hackage and Stackage, my thinking is that most _users_ will probably want to know how to add a dependency on `monad-bayes` to their own project, i.e. what to put in their `.cabal` file or `stack.yaml`.

For people who actually want to clone `monad-bayes` and hack on it, the Readme should definitely mention either the `ln` solution you suggested or the `--stack-yaml` flag. The instructions are definitely incomplete as they are right now.

**Comment by mboes** [comment]
It would be fair to have a `stack.yaml`, i.e. a default Stack configuration file.

**Comment by curiousleo** [comment]
> It would be fair to have a `stack.yaml`, i.e. a default Stack configuration file.

I've created a symlink from `stack.yaml -> stack-ghc881.yaml` here: https://github.com/tweag/monad-bayes/pull/97/commits/1d88f78b1c006079246848f97ed5691d4a8bf778#diff-fafd0cdcd559a7b124cc61c29413fb54.

I've checked that this has the desired effect: `stack test` etc. works and uses the snapshot defined in `stack-ghc881.yaml`.
