### ISSUE TITLE
Classical MCMC with Metropolis-Hasting proposals

### ISSUE THREAD

**Issue by dschrempf** [tweag/monad-bayes#98]
Hello,

I fail to implement a classical MCMC method with Metropolis-Hasting (MH) proposals. How can I define the proposal distribution conditioned on the current state? I looked at the code of the MH proposal, and it is hidden in the `Trace` data type. The acceptance ratio is computed using the likelihood ratio of the proposed vs. current state (and some correction factor which I do not understand; it involves the number of sampled variables?).

To me, this is a standard Metropolis update, and not a Metropolis-Hastings update which includes a proposal distribution dependent on the current state. Can you comment on this?

Thank you for your help!
Dominik

As a side question: Is it possible to run an MCMC with MH proposals without using `Trace`. I.e., by just saving or outputting the current state of the chain?

**Comment by curiousleo** [comment]
@MMesch, would you mind taking a look?

**Comment by simeoncarstens** [comment]
Details on the trace Metropolis-Hastings algorithm implemented in `monad-bayes` can be found in the following paper: https://dl.acm.org/doi/10.1145/3158148, more specifically, in section 7.
@MMesch and I will have a closer look at your questions.

**Comment by dschrempf** [comment]
From what I can see after a brief look at the mentioned section: the proposal kernel maps from the trace to the new state, but I am not sure how to program this, since the trace has a random order. Also, in Metropolis-Hastings, the proposal usually only depends on the current state (Markov property). I still don't see how the proposal distribution is influencing the acceptance ratio. Thanks anyways, for having a look at this!

**Comment by MMesch** [comment]
@dschrempf , I briefly looked into this as well last year. I remember that I also encountered this:

> but I am not sure how to program this, since the trace has a random order

I might have time in 2 or 3 weeks to have a closer look. Meanwhile, let us know if you already have anything running or any other thoughts!

**Comment by reubenharry** [comment]
@dschrempf Belatedly answering this: the MCMC implemented in monad-bayes is a version which is totally agnostic to the probabilistic program in question. That is to say, no matter what probabilistic program you write, you can run a correct-by-design MCMC walk on it. This generality means that the MCMC implementation is quite inflexible: you don't get to decide the nature of the proposal.

What you're asking for is the more familiar version of MCMC where you supply a proposal, and the code does a random walk based on that (using MH). I've implemented this locally (using the `pipes` library) and I'll plan to add this to monad-bayes in due course.

**Comment by dschrempf** [comment]
That's great!

In the meantime, I have been working on and have been using a separate library [mcmc](https://hackage.haskell.org/package/mcmc). However, it is tailored to MCMC applications, and not to the probabilistic programs such as monad-bayes.
